language: java
sudo: required

jdk:
  - oraclejdk8

install: true
script:
  - ./gradlew build --stacktrace --no-daemon

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    recipients:
      - ase@enonic.com
      - jsi@enonic.com
    on_success: change
    on_failure: always